// <auto-generated />
using System;
using AvaloniaApplication2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AvaloniaApplication2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417135556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("clientComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("clientUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("endsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("masterServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("startsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("clientUserId");

                    b.HasIndex("masterServiceId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.BalanceTopUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("cardId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("completedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("externalPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<int>("walletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("cardId");

                    b.HasIndex("walletId");

                    b.ToTable("balance_topups", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("directionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("directionId", "name")
                        .IsUnique();

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("directions", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.MasterProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("experienceYears")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("qualificationLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("qualificationLevelId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("master_profiles", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.MasterService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("customPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("masterProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("serviceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("serviceId");

                    b.HasIndex("masterProfileId", "serviceId")
                        .IsUnique();

                    b.ToTable("master_services", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.PaymentCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("expMonth")
                        .HasColumnType("integer");

                    b.Property<int>("expYear")
                        .HasColumnType("integer");

                    b.Property<string>("holderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("isDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("maskedPan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("paymentToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("paymentToken")
                        .IsUnique();

                    b.HasIndex("userId");

                    b.ToTable("payment_cards", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.QualificationApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("masterProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("requestedLevelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("reviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("reviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("masterProfileId");

                    b.HasIndex("requestedLevelId");

                    b.HasIndex("reviewedByUserId");

                    b.ToTable("qualification_applications", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.QualificationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("qualification_levels", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("appointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("authorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("appointmentId")
                        .IsUnique();

                    b.HasIndex("authorUserId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.ShopService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("basePrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("collectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("durationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("imagePath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("collectionId", "name")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.HasIndex("userId", "roleId")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("lastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.ApplicationUser", "clientUser")
                        .WithMany("clientAppointments")
                        .HasForeignKey("clientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.MasterService", "masterService")
                        .WithMany("appointments")
                        .HasForeignKey("masterServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("clientUser");

                    b.Navigation("masterService");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.BalanceTopUp", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.PaymentCard", "card")
                        .WithMany("balanceTopUps")
                        .HasForeignKey("cardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.Wallet", "wallet")
                        .WithMany("balanceTopUps")
                        .HasForeignKey("walletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("card");

                    b.Navigation("wallet");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Collection", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.Direction", "direction")
                        .WithMany("collections")
                        .HasForeignKey("directionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("direction");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.MasterProfile", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.QualificationLevel", "qualificationLevel")
                        .WithMany("masterProfiles")
                        .HasForeignKey("qualificationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.ApplicationUser", "user")
                        .WithOne("masterProfile")
                        .HasForeignKey("AvaloniaApplication2.Domain.Entities.MasterProfile", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("qualificationLevel");

                    b.Navigation("user");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.MasterService", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.MasterProfile", "masterProfile")
                        .WithMany("masterServices")
                        .HasForeignKey("masterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.ShopService", "service")
                        .WithMany("masterServices")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("masterProfile");

                    b.Navigation("service");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.PaymentCard", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.ApplicationUser", "user")
                        .WithMany("paymentCards")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.QualificationApplication", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.MasterProfile", "masterProfile")
                        .WithMany("qualificationApplications")
                        .HasForeignKey("masterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.QualificationLevel", "requestedLevel")
                        .WithMany("qualificationApplications")
                        .HasForeignKey("requestedLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.ApplicationUser", "reviewedByUser")
                        .WithMany("reviewedQualificationApplications")
                        .HasForeignKey("reviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("masterProfile");

                    b.Navigation("requestedLevel");

                    b.Navigation("reviewedByUser");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Review", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.Appointment", "appointment")
                        .WithOne("review")
                        .HasForeignKey("AvaloniaApplication2.Domain.Entities.Review", "appointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.ApplicationUser", "authorUser")
                        .WithMany("reviews")
                        .HasForeignKey("authorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("appointment");

                    b.Navigation("authorUser");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.ShopService", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.Collection", "collection")
                        .WithMany("services")
                        .HasForeignKey("collectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("collection");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.Role", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvaloniaApplication2.Domain.Entities.ApplicationUser", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("AvaloniaApplication2.Domain.Entities.ApplicationUser", "user")
                        .WithOne("wallet")
                        .HasForeignKey("AvaloniaApplication2.Domain.Entities.Wallet", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("clientAppointments");

                    b.Navigation("masterProfile");

                    b.Navigation("paymentCards");

                    b.Navigation("reviewedQualificationApplications");

                    b.Navigation("reviews");

                    b.Navigation("userRoles");

                    b.Navigation("wallet");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("review");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Collection", b =>
                {
                    b.Navigation("services");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Direction", b =>
                {
                    b.Navigation("collections");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.MasterProfile", b =>
                {
                    b.Navigation("masterServices");

                    b.Navigation("qualificationApplications");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.MasterService", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.PaymentCard", b =>
                {
                    b.Navigation("balanceTopUps");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.QualificationLevel", b =>
                {
                    b.Navigation("masterProfiles");

                    b.Navigation("qualificationApplications");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Role", b =>
                {
                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.ShopService", b =>
                {
                    b.Navigation("masterServices");
                });

            modelBuilder.Entity("AvaloniaApplication2.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("balanceTopUps");
                });
#pragma warning restore 612, 618
        }
    }
}
